name: 'Main Pipeline' 

on:
#   push:
#     branches:
#     - "main"
#   pull_request:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  checks: write
  pull-requests: write

jobs:
  test:
    name: Terraform Test
    uses: OneWorldGTM/owgtm-templates/.github/workflows/terraform-test.yml@main
    secrets: inherit
    with:
      docs_output: "../README.md"

#   set-matrix:
#     name: Set Matrix
#     uses: OneWorldGTM/owgtm-templates/.github/workflows/set-matrix.yml@main
#     with:
#       json_path: 'environments.json'
#       env_deploy_list: '["dev","test","preprod","prod"]'

#   Plan:
#     needs: [ test, set-matrix ]
#     name: Terraform Plan - ${{ matrix.env }}
#     strategy:
#       max-parallel: 1
#       matrix: ${{fromJson(needs.set-matrix.outputs.matrix)}}
#     uses: OneWorldGTM/owgtm-templates/.github/workflows/terraform-plan.yml@main
#     secrets: inherit
#     with:
#       environment: ${{ matrix.env }}
#       region: ${{ matrix.region }}
#       role_to_assume: ${{ matrix.role_to_assume }}
#       #tf_destroy_all_resources: ${{ matrix.tf_destroy_all_resources}}

#   Apply:
#     needs: [ Plan, set-matrix ]
#     name: Terraform Apply - ${{ matrix.env }}
#     strategy:
#       max-parallel: 1
#       matrix: ${{fromJson(needs.set-matrix.outputs.matrix)}}
#     uses: OneWorldGTM/owgtm-templates/.github/workflows/terraform-apply.yml@main
#     secrets: inherit
#     with:
#       environment: ${{ matrix.env }}
#       env_deploy_list: ${{ needs.set-matrix.outputs.env_deploy_list }}
#       region: ${{ matrix.region }}
#       role_to_assume: ${{ matrix.role_to_assume }}
#       #tf_destroy_all_resources: ${{ matrix.tf_destroy_all_resources}}